name: Build PS5 Payload

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-15 lld-15 git
          
      - name: Install PS5 SDK
        run: |
          git clone https://github.com/ps5-payload-dev/sdk.git
          cd sdk
          sudo make DESTDIR=/opt/ps5-payload-sdk install
          
      - name: Compile
        run: |
          export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
          make
          
      - name: Upload ELF
        uses: actions/upload-artifact@v4
        with:
          name: ps5-syslang-elf
          path: ps5-syslang.elf
